# @package agent
_target_: agent.icm_becl.BECLAgent
name: icm_becl
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
icm_rep_dim: 512
stddev_schedule: 0.2
stddev_clip: 0.3
icm_scale: 1.0
skill_dim: 16
update_skill_every_step: 50
nstep: 3
batch_size: 1024
init_critic: true
knn_rms: false
knn_k: 12
knn_avg: true
knn_clip: 0.0
update_encoder: ${update_encoder}

temperature: 0.5
contrastive_scale: 1.0
skill: 0